# nodejs-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        imagePullPolicy: Always      
        image: arthurescriou/node-redis:1.0.5 # Image du conteneur Node.js
        env:
        - name: REDIS_URL
          value: "redis://redis-master.default.svc.cluster.local:6379"
        - name: REDIS_REPLICAS_URL
          value: "redis://redis-slave.default.svc.cluster.local:6379"
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
