# prometheus-configmap.yaml  
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'nodejs'
      static_configs:
      - targets: ['nodejs-app-service.default.svc.cluster.local:8080']
    - job_name: 'redis'
      static_configs:
      - targets: ['redis-exporter.default.svc.cluster.local:9121']
