# redis-slave-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  replicas: 2  # Número de réplicas de slaves
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - name: redis-slave
        image: redis:alpine
        command: ["redis-server", "--slaveof", "redis-master.default.svc.cluster.local", "6379"]
        ports:
        - containerPort: 6379
